codecov: true
coveralls: true

language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
 allow_failures:
 - julia: nightly
 - julia: 1.3

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
