codecov: true
coveralls: true

language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
 allow_failures:
 - julia: nightly
 - julia: 1.3
